[project]
name = "backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "hsauihh", email = "woshidairuiqi@outlook.com" }
]
requires-python = ">=3.13"
dependencies = [
    "fastapi[standard]>=0.141.1",
    "pypinyin>=0.55.0",
    "requests>=2.34.2",
    "snownlp>=0.12.3",
]
